---
title: "Change Point Analysis"
author: "Erik Carrion"
date: "21 APril 2023"
output:
  pdf_document: default
  html_notebook: default
subtitle: Nile River Flow Data
---
 

```{r}
# Load dependencies
library(tidyverse)

# Load data. Create Data Frame
data("Nile")
data <- data.frame(year=seq(1871, 1970), flow = array(Nile))
```

```{r}
# set seed
set.seed(4242, sample.kind="Rounding")

# Set X, N
X <- array(data$flow)
N <- dim(data)[1]

# set priors
# Priors for f(x)
tau <- 1/var(X)

# priors for tau
a0 <- b0 <- .01

#priors for alpha.0 and alpha.1
alpha.0 <- alpha.1 <- mean(X)
tau.0 <- tau.1 <- 1e-8

# Iterations
B <- 10^4

# Prior for the proposal distribution
cp <- median(data$year)

# Width of proposal distribution
delta <- .5

# Storage Monitors
mon.cp <- mon.tau <- mon.alpha0 <- mon.alpha1 <- numeric(B)


# Gibbs Sampler
for(i in 1:B){
  # Split Data
  X0 <- data$flow[data$year < cp]
  X1 <- data$flow[data$year >= cp]
  
  # estimate alpha.0, and alpha.1
  n0 <-length(X0)
  tau0 <- tau.0 + n0*tau
  mu.alpha.0 <- sum(X0)*tau / tau0
  
  n1 <- length(X1)
  tau1 <- tau.1 + n1*tau
  mu.alpha.1 <- sum(X1)*tau / tau1
  
  alpha.0 <- rnorm(1, mu.alpha.0, 1/sqrt(tau0))
  alpha.1 <- rnorm(1, mu.alpha.1, 1/sqrt(tau1))
  
  # estimate tau
  a <- a0 + N/2
  b <- b0 + 0.5*sum(((X-alpha.0)^2)[data$year < cp]) + 0.5*sum(((X-alpha.1)^2)[data$year >= cp]) 
  tau <- rgamma(1, a, b)
  sdx <- 1/sqrt(tau)
  
  # Given alpha.0, alpha.1, tau, and cp propose a cp.new
  cp.new <-rnorm(1, cp, delta)
  
  # evaluate Likelihood of the data under the new change point
  logR <- (sum(dnorm(data$flow[data$year <  cp.new], alpha.0, sd=sdx, log=T)) +
           sum(dnorm(data$flow[data$year >= cp.new], alpha.1, sd=sdx, log=T))) -
          (sum(dnorm(data$flow[data$year < cp], alpha.0, sd=sdx, log=T)) +
           sum(dnorm(data$flow[data$year >= cp], alpha.1, sd=sdx, log=T))) # +
    # difference in log priors for cp
    # 0 - 
    # Log of Proposal Ratio
    # 0
  
  # Check if rand unif is less than logR
  logU <- log(runif(1,0,1))
  
  if(logU < logR){cp <- cp.new}
  
  # Update storage monitors
  mon.cp[i] <- cp
  mon.tau[i] <- tau
  mon.alpha0 <- alpha.0
  mon.alpha1 <- alpha.1
  
}

```
Summarize our findings

```{r}
print("Summary of CP")
summary(mon.cp) 

print("Summary of Tau")
summary(mon.tau)

print("Summary of Alpha 0")
summary(mon.alpha0)

print("Summary of Alpha 1")
summary(mon.alpha1)


```

